#!/bin/bash

# install pytesseract
#https://stackabuse.com/pytesseract-simple-python-optical-character-recognition/

pip install pipenv
mkdir ocr_server && cd ocr_server && pipenv install --three

pip install pillow
pip install pytesseract
pipenv shell
pipenv install pytesseract Pillow
try:
    from PIL import Image
except ImportError:
    import Image
import pytesseract

def ocr_core(filename):
    """
    This function will handle the core OCR processing of images.
    """
    text = pytesseract.image_to_string(Image.open(filename))  # We'll use Pillow's Image class to open the image and pytesseract to detect the string in the image
    return text

print(ocr_core('images/ocr_example_1.png'))

